In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [8]:
z=np.zeros((3,4))

In [9]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
vals = np.arange(10, 25, 5)


In [11]:
vals

array([10, 15, 20])

In [12]:
lin_vals = np.linspace(0, 2, 9)


In [13]:
lin_vals

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
const_2x2 = np.full((2, 2), 7)


In [17]:
const_2x2

array([[7, 7],
       [7, 7]])

In [18]:
identity = np.eye(2)
random_mat = np.random.rand(2, 2)

In [19]:
print(a.shape, a.ndim, a.size)
print(b.shape, b.ndim, b.size)
print(c.shape, c.ndim, c.size)


(3,) 1 3
(2, 3) 2 6
(2, 2, 3) 3 12


In [20]:
print(b.dtype, b.dtype.name)
b_int = b.astype(int)

float64 float64


In [21]:
add_ab = a + b
sub_ab = a - b


In [22]:
mul_bb = b * b
div_bb = b / b


In [23]:
sqrt_b = np.sqrt(b)

In [24]:
total = np.sum(b)
minimum = np.min(b)
maximum = np.max(b)
cumulative = np.cumsum(b)
mean = np.mean(b)
median = np.median(b)
std_dev = np.std(b)